### ISSUE TITLE
Login v1

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/ai-experience-sharing-platform#1]
As a platform stakeholder, in order to comply with privacy requirements, I would like the MVP site to not be publicly accessible.

Features & Details:

1. AI sharing platform and its content cannot be accessed publicly 
2. The site access is locked by either IP whitelist, basic auth, or any other options can be discussed with  the project team
3. Investigate d2.gsa.gov options for authentication piece

## Tasks
 - [x] Research Federalist Solution: Tim sends email to Federalist
 - [x] Research Gatsby Solution
 - [x] Implement Password Protection on Site
