### ISSUE TITLE
Content Management

### ISSUE THREAD

**Issue by kdicker1** [GSA/ai-experience-sharing-platform#13]
As a content curator, in order to provide the most up-to-date content for AI platform users, I would like to be able to manage the content for use cases and resources pages.

Features and Details: 
1. Content curator can manage the pages via the content repository (Federalist?)

## Tasks
 - [x] Configure Netlify collections
 - [x] Configure Netflify Content Templates
 - [x] Get peeps WRITE access to Github repo

 - cnelsonflexion
 - Robin (TBD)
 - Steven (TBD)

 - [x] configure content edits to apply to env branch
