### ISSUE TITLE
Content Categories

### ISSUE THREAD

**Issue by kdicker1** [GSA/ai-experience-sharing-platform#15]
As a content curator, in order to organize the content based on the main navigation, I would like to be able to assign content to categories.

Features & Details: 
1. Content curator can assign newly created content to categories. 
2. Content curator can modify the categories for existing content

## Tasks
 - [ ] Define Category List
 - [ ] Research Categories as content
 - [ ] Implement Category List
