### ISSUE TITLE
Content Items/ Pages

### ISSUE THREAD

**Issue by kdicker1** [GSA/ai-experience-sharing-platform#17]
As a content curator, in order to provide accurate and detailed use case content and up to date AI resources for site users, I would like to be able to manage the content items and content fields for each item.	

Features & Details: 
1. Admin user can create, edit and delete content items/pages.	
2. Content curator can organize the detailed content into paragraphs under multiple headers on the page.	
Example of header row:
Content paragraph headers:  title, short description, long description, owners/participants, publish date, background, technical requirements, datasets, code, support documents, videos, results/outcomes. https://drive.google.com/file/d/1WEuSgi59K0HXfdHB4f1qjyQ1yTxtkCg-/view

## Tasks
 - [ ] Adding Article Content Type
 - [ ] Add Page Content Type
 - [ ] Implement MDX for content modules
 - [ ] Implement frontmatter
